### PR TITLE
evaluate: initialize report[pair]

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Review by bertsky — COMMENTED** [review]
Does this fix a bug you actually observed, or did you conclude that by reviewing the code?

IIRC this should never be necessary as the dict already gets initialized in https://github.com/ASVLeipzig/cor-asv-ann/blob/be73c96561107510683083d6d3064144ef342b21/ocrd_cor_asv_ann/wrapper/evaluate.py#L82

**Comment by kba** [comment]
Without this I get

```
14:19:39.112 INFO processor.EvaluateLines -     0 lines 0.000±0.000 CER phys_0001 / OCR-D-GT-SEG-BLOCK vs OCR-D-OCR-TESS                                                                 
Traceback (most recent call last):                                                                                                                                      
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/bin/ocrd-cor-asv-ann-evaluate", line 8, in <module>                                                                      
    sys.exit(ocrd_cor_asv_ann_evaluate())                                                                                                                                                     
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/click/core.py", line 829, in __call__                                                        
    return self.main(*args, **kwargs)                                                                                                                                                         
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/click/core.py", line 782, in main                                                            
    rv = self.invoke(ctx)                                                                                                                                                                     
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/click/core.py", line 1066, in invoke                                                         
    return ctx.invoke(self.callback, **ctx.params)                                                                                                                       
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/click/core.py", line 610, in invoke                                     
    return callback(*args, **kwargs)                                                                                                                                                          
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/ocrd_cor_asv_ann/wrapper/cli.py", line 16, in ocrd_cor_asv_ann_evaluate                      
    return ocrd_cli_wrap_processor(EvaluateLines, *args, **kwargs)                                                                                                                            
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/ocrd/decorators/__init__.py", line 91, in ocrd_cli_wrap_processor                            
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)                                                                
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/ocrd/processor/helpers.py", line 72, in run_processor                                        
    processor.process()                                                                                                                                                                       
  File "/home/kba/monorepo/ocrd_all/venv/local/sub-venv/headless-tf1/lib/python3.6/site-packages/ocrd_cor_asv_ann/wrapper/evaluate.py", line 125, in process                                  
    report[pair]['length'] = file_edits[i].length                                                                                                                                             
KeyError: 'OCR-D-GT-SEG-BLOCK,OCR-D-OCR-TESS' 
```

**Comment by kba** [comment]
> > In this case, the line-id-alignment didn't work. With files that use the same line-id schema, it is not necessary.
> 
> I still do not quite understand. Disjunct line IDs should not be able to cause this. The only explanation that I manage to envision is that a **page** ID is missing from the first (GT) fileGrp. That latter case seems to be unsupported if `zip_input_files` does not rule it out properly (which it did before we moved it to core).
> 
> But then you patch is not the right kind of fix.
> 
> Sorry for being so cautious, but I want to make sure we are not missing some bigger problem here.

 I cannot now reproduce the issue because I've deleted the files that triggered this. I was unsure myself why this would happen because I do not expect such an obvious mistake in your code. If I can recreate the circumstances, I'll let you know, otherwise feel free to close as invalid.

**Review by bertsky — APPROVED** [review]

**Comment by bertsky** [comment]
Thanks!

**Pull request merged**
